{% set version = "0.20.7" %}

package:
  name: azure-servicemanagement-legacy
  version: {{ version }}

source:
  fn: azure-servicemanagement-legacy-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-servicemanagement-legacy/azure-servicemanagement-legacy-{{ version }}.zip
  md5: 48f651b27db7121a00006cf48733f67c


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
    - azure-common
    - requests
    - pyopenssl
  run:
    - python
    - azure-common
    - requests
    - pyopenssl

test:
  imports:
    - azure
    - azure.servicemanagement
    - azure.servicemanagement._http
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: Microsoft Azure Legacy Service Management Client Library for Python

extra:
  recipe-maintainers:
    - Maxyme
