{% set version = "0.20.6" %}

package:
  name: azure-servicemanagement-legacy
  version: {{ version }}

source:
  fn: azure-servicemanagement-legacy-{{ version }}.zip
  url: https://pypi.org/packages/source/a/azure-servicemanagement-legacy/azure-servicemanagement-legacy-{{ version }}.zip
  md5: 4c97f1c9013d9caba6628488c7e24dd2
  

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - azure-common
    - requests
    - pyopenssl
  run:
    - python >={{ python_min }}
    - azure-common
    - requests
    - pyopenssl

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.servicemanagement
    - azure.servicemanagement._http
  commands:
    - python -m unittest discover -p "test_*.py"    

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Legacy Service Management Client Library for Python'

extra:
  recipe-maintainers:
    - Maxyme
